apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  ports:
  - port: 25565
    targetPort: 25565
    nodePort: 25565
    protocol: TCP
  selector:
    app: minecraft
  type: NodePort 