apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT_NAME}
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      imagePullSecrets:
      - name: ghcr-auth-tmcp
      containers:
      - name: minecraft
        image: ${REGISTRY_URL}/minecraft-server:${IMAGE_TAG}
        ports:
        - containerPort: 25565
          name: minecraft
        env:
        - name: EULA
          value: "TRUE"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        - name: minecraft-config
          mountPath: /data/server.properties
          subPath: server.properties
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-pvc
      - name: minecraft-config
        configMap:
          name: minecraft-config 