name: Deploy Minecraft Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip jq gettext-base curl
        echo "Skipping git-lfs due to quota issues"

    - name: Check environment
      run: |
        echo "Checking environment..."
        whoami
        pwd
        echo "Docker version:"
        docker --version || echo "Docker not found"
        echo "System info:"
        uname -a
        echo "Available disk space:"
        df -h

    - name: Checkout code (without LFS)
      uses: actions/checkout@v3
      with:
        lfs: false

    - name: Create server files manually
      run: |
        # Create directory for server files
        mkdir -p server_files
        
        # Create eula.txt
        echo "eula=true" > server_files/eula.txt
        echo "Created eula.txt file"
        
        # Create docker-entrypoint.sh
        cat > server_files/docker-entrypoint.sh << 'EOF'
        #!/bin/bash
        set -e

        # Print Minecraft server version
        echo "Starting Minecraft server with the following settings:"
        echo "Memory: ${MIN_MEMORY} - ${MAX_MEMORY}"
        echo "Server properties loaded from: /data/server.properties"

        # Set memory settings in environment for the start.sh script to use
        export JAVA_OPTS="-Xms${MIN_MEMORY} -Xmx${MAX_MEMORY}"

        # Check if start.sh exists
        if [ -f "/data/start.sh" ]; then
          echo "Found start.sh script, executing..."
          chmod +x /data/start.sh
          exec /data/start.sh
        else
          echo "No start.sh found, falling back to direct Java execution"
          
          # Check if server.jar exists
          if [ ! -f "/data/server.jar" ]; then
            echo "Error: server.jar not found!"
            exit 1
          fi
          
          # Start the Minecraft server directly
          echo "Starting Minecraft server..."
          exec java -Xms${MIN_MEMORY} -Xmx${MAX_MEMORY} -jar server.jar nogui
        fi
        EOF
        
        chmod +x server_files/docker-entrypoint.sh
        echo "Created docker-entrypoint.sh script"
        
        # Create a basic server.properties file if needed
        if [ ! -f "server_files/server.properties" ]; then
          cat > server_files/server.properties << 'EOF'
        difficulty=normal
        gamemode=survival
        max-players=20
        motd=Kubernetes Minecraft Server
        pvp=true
        allow-nether=true
        enable-command-block=false
        spawn-protection=16
        view-distance=10
        EOF
          echo "Created basic server.properties file"
        fi
        
        # Download server.jar if needed
        if [ ! -f "server_files/server.jar" ]; then
          echo "Downloading server.jar..."
          curl -o server_files/server.jar https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar
          echo "Downloaded server.jar"
        fi
        
        echo "Server files created successfully"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract build args from config
      id: build_args
      run: |
        # Set default values
        MIN_MEMORY="2G"
        MAX_MEMORY="4G"
        SERVER_PORT=25565
        
        # Try to read from config.json if it exists
        if [ -f "minecraft_server/config.json" ]; then
          MIN_MEMORY=$(jq -r '.server.memory.min // "2G"' minecraft_server/config.json)
          MAX_MEMORY=$(jq -r '.server.memory.max // "4G"' minecraft_server/config.json)
        fi
        
        echo "min_memory=$MIN_MEMORY" >> $GITHUB_OUTPUT
        echo "max_memory=$MAX_MEMORY" >> $GITHUB_OUTPUT
        echo "server_port=$SERVER_PORT" >> $GITHUB_OUTPUT
        
        echo "Using memory settings: Min=$MIN_MEMORY, Max=$MAX_MEMORY"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/minecraft-server:${{ github.sha }}
        build-args: |
          MIN_MEMORY=${{ steps.build_args.outputs.min_memory }}
          MAX_MEMORY=${{ steps.build_args.outputs.max_memory }}
          SERVER_PORT=${{ steps.build_args.outputs.server_port }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    
    - name: Update Kubernetes deployment
      run: |
        export REGISTRY_URL=ghcr.io/${{ github.repository_owner }}
        export IMAGE_TAG=${{ github.sha }}
        export DEPLOYMENT_NAME=$(jq -r '.deployment.name' minecraft_server/config.json || echo "minecraft-server")
        
        # Replace variables in all Kubernetes files
        for file in k8s/*.yaml; do
          envsubst < $file > ${file}.updated
          mv ${file}.updated $file
        done
        
        # Apply Kubernetes configurations
        kubectl apply -f k8s/ 