name: Deploy Minecraft Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      modpack_id:
        description: 'CurseForge modpack ID (e.g., 6048096 for Better MC Forge)'
        required: false
        default: '6048096'

jobs:
  build-and-deploy:
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip jq gettext-base curl python3 python3-pip
        echo "Skipping git-lfs due to quota issues"
        pip3 install requests beautifulsoup4

    - name: Check environment
      run: |
        echo "Checking environment..."
        whoami
        pwd
        echo "Docker version:"
        docker --version || echo "Docker not found"
        echo "System info:"
        uname -a
        echo "Available disk space:"
        df -h

    - name: Checkout code (without LFS)
      uses: actions/checkout@v3
      with:
        lfs: false

    - name: Download and extract server pack
      run: |
        # Create directory for server files
        mkdir -p server_files
        
        # Create a Python script to handle CurseForge downloads
        cat > get_curseforge_download.py << 'EOF'
        import requests
        import sys
        import json
        import re
        from bs4 import BeautifulSoup
        from urllib.parse import urljoin

        def get_direct_download_url(download_page_url):
            try:
                # Set up headers to mimic a browser
                headers = {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
                    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                    'Accept-Language': 'en-US,en;q=0.5',
                    'DNT': '1',
                    'Connection': 'keep-alive',
                    'Upgrade-Insecure-Requests': '1',
                }

                # First get the download page
                print(f"Accessing download page: {download_page_url}", file=sys.stderr)
                session = requests.Session()
                response = session.get(download_page_url, headers=headers)
                response.raise_for_status()

                # Parse the page
                soup = BeautifulSoup(response.text, 'html.parser')
                
                # Look for the server files download button
                download_buttons = soup.find_all('a', string=re.compile('Download', re.IGNORECASE))
                for button in download_buttons:
                    href = button.get('href')
                    if href and '/download/' in href:
                        direct_url = urljoin('https://www.curseforge.com', href)
                        print(f"Found download link: {direct_url}", file=sys.stderr)
                        
                        # Follow the download link
                        print("Following download link...", file=sys.stderr)
                        response = session.get(direct_url, headers=headers, allow_redirects=True)
                        response.raise_for_status()
                        
                        # The final URL should be the direct file download
                        final_url = response.url
                        print(f"Final download URL: {final_url}", file=sys.stderr)
                        return final_url

                raise Exception("No download button found on the page")
                
            except Exception as e:
                print(f"Error getting download URL: {str(e)}", file=sys.stderr)
                return None

        if __name__ == "__main__":
            download_page_url = sys.argv[1]
            direct_url = get_direct_download_url(download_page_url)
            if direct_url:
                print(direct_url)
            else:
                sys.exit(1)
        EOF
        
        # Get the server pack URL from config.json
        if [ -f "minecraft_server/config.json" ]; then
          SERVER_PACK_URL=$(jq -r '.server.server_pack_url // empty' minecraft_server/config.json)
          if [ -n "$SERVER_PACK_URL" ]; then
            echo "Using server pack URL from config.json: $SERVER_PACK_URL"
          else
            echo "No server pack URL found in config.json"
            exit 1
          fi
        else
          echo "Config file not found"
          exit 1
        fi
        
        # Get the direct download URL using the Python script
        echo "Getting direct download URL..."
        DIRECT_URL=$(python3 get_curseforge_download.py "$SERVER_PACK_URL")
        
        if [ -z "$DIRECT_URL" ]; then
          echo "Failed to get direct download URL"
          exit 1
        fi
        
        echo "Got direct download URL: $DIRECT_URL"
        
        # Download the server pack
        echo "Downloading server pack..."
        curl -L -o server_pack.zip "$DIRECT_URL"
        echo "Download complete"
        
        # Extract the server pack
        echo "Extracting server pack..."
        unzip -q server_pack.zip -d server_files
        echo "Extraction complete"
        
        # Create eula.txt
        echo "Creating eula.txt file..."
        echo "eula=true" > server_files/eula.txt
        echo "eula.txt created successfully"
        
        # Create docker-entrypoint.sh
        echo "Creating docker-entrypoint.sh..."
        cat > server_files/docker-entrypoint.sh << 'EOF'
        #!/bin/bash
        set -e

        # Print Minecraft server version
        echo "Starting Minecraft server with the following settings:"
        echo "Memory: ${MIN_MEMORY} - ${MAX_MEMORY}"
        echo "Server properties loaded from: /data/server.properties"

        # Set memory settings in environment for the start.sh script to use
        export JAVA_OPTS="-Xms${MIN_MEMORY} -Xmx${MAX_MEMORY}"

        # Check if start.sh exists
        if [ -f "/data/start.sh" ]; then
          echo "Found start.sh script, executing..."
          chmod +x /data/start.sh
          exec /data/start.sh
        else
          # Look for other startup scripts
          if [ -f "/data/startserver.sh" ]; then
            echo "Found startserver.sh script, executing..."
            chmod +x /data/startserver.sh
            exec /data/startserver.sh
          elif [ -f "/data/run.sh" ]; then
            echo "Found run.sh script, executing..."
            chmod +x /data/run.sh
            exec /data/run.sh
          elif [ -f "/data/server-start.sh" ]; then
            echo "Found server-start.sh script, executing..."
            chmod +x /data/server-start.sh
            exec /data/server-start.sh
          else
            echo "No startup script found, falling back to direct Java execution"
            
            # Find the server jar file
            SERVER_JAR=$(find /data -name "forge-*.jar" -o -name "server.jar" -o -name "*server*.jar" | head -n 1)
            
            if [ -z "$SERVER_JAR" ]; then
              echo "Error: No server jar found!"
              exit 1
            fi
            
            echo "Found server jar: $SERVER_JAR"
            
            # Start the Minecraft server directly
            echo "Starting Minecraft server..."
            cd /data
            exec java -Xms${MIN_MEMORY} -Xmx${MAX_MEMORY} -jar $(basename $SERVER_JAR) nogui
          fi
        fi
        EOF
        
        chmod +x server_files/docker-entrypoint.sh
        echo "docker-entrypoint.sh created successfully"
        
        # List the extracted files
        echo "Listing extracted files:"
        find server_files -type f -name "*.jar" | sort
        find server_files -type f -name "*.sh" | sort
        
        echo "Server files prepared successfully"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract build args from config
      id: build_args
      run: |
        # Set default values
        MIN_MEMORY="4G"
        MAX_MEMORY="8G"
        SERVER_PORT=25565
        
        # Try to read from config.json if it exists
        if [ -f "minecraft_server/config.json" ]; then
          MIN_MEMORY=$(jq -r '.server.memory.min // "4G"' minecraft_server/config.json)
          MAX_MEMORY=$(jq -r '.server.memory.max // "8G"' minecraft_server/config.json)
        fi
        
        echo "min_memory=$MIN_MEMORY" >> $GITHUB_OUTPUT
        echo "max_memory=$MAX_MEMORY" >> $GITHUB_OUTPUT
        echo "server_port=$SERVER_PORT" >> $GITHUB_OUTPUT
        
        echo "Using memory settings: Min=$MIN_MEMORY, Max=$MAX_MEMORY"
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/minecraft-server:${{ github.sha }}
        build-args: |
          MIN_MEMORY=${{ steps.build_args.outputs.min_memory }}
          MAX_MEMORY=${{ steps.build_args.outputs.max_memory }}
          SERVER_PORT=${{ steps.build_args.outputs.server_port }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    
    - name: Update Kubernetes deployment
      run: |
        export REGISTRY_URL=ghcr.io/${{ github.repository_owner }}
        export IMAGE_TAG=${{ github.sha }}
        export DEPLOYMENT_NAME=$(jq -r '.deployment.name' minecraft_server/config.json || echo "minecraft-server")
        
        # Replace variables in all Kubernetes files
        for file in k8s/*.yaml; do
          envsubst < $file > ${file}.updated
          mv ${file}.updated $file
        done
        
        # Apply Kubernetes configurations
        kubectl apply -f k8s/ 